config/routes.rb
Rails.application.routes.draw do
  resources :text_wrappers
  root "text_wrappers#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/text_wrapper.rb
class TextWrapper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/text_wrappers_controller.rb
class TextWrappersController < ApplicationController
  before_action :set_text_wrapper, only: [:show, :edit, :update, :destroy]

  def index
    @text_wrappers = TextWrapper.all
  end

  def show
  end

  def new
    @text_wrapper = TextWrapper.new
  end

  def edit
  end

  def create
    @text_wrapper = TextWrapper.new(text_wrapper_params)
    @text_wrapper.text = wrap(@text_wrapper.text, @text_wrapper.line_width, "<span></span>")
    respond_to do |format|
      if @text_wrapper.save
        format.html { redirect_to @text_wrapper, notice: 'Text wrapper was successfully created.' }
        format.json { render :show, status: :created, location: @text_wrapper }
      else
        format.html { render :new }
        format.json { render json: @text_wrapper.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @text_wrapper.update(text_wrapper_params)
        format.html { redirect_to @text_wrapper, notice: 'Text wrapper was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_wrapper }
      else
        format.html { render :edit }
        format.json { render json: @text_wrapper.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @text_wrapper.destroy
    respond_to do |format|
      format.html { redirect_to text_wrappers_url, notice: 'Text wrapper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_text_wrapper
      @text_wrapper = TextWrapper.find(params[:id])
    end

    def text_wrapper_params
      params.require(:text_wrapper).permit(:line_width, :text)
    end
    
    def wrap(text, length = 80, character = $/)
        text.scan(/\S.{0,#{length-2}}\S(?=\s|$)|\S+/).join(character)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/text_wrappers_helper.rb
module TextWrappersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiAcrelec</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/text_wrappers/_form.html.erb
<%= form_with(model: text_wrapper, local: true) do |form| %>
  <% if text_wrapper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text_wrapper.errors.count, "error") %> prohibited this text_wrapper from being saved:</h2>

      <ul>
      <% text_wrapper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :line_width %>
    <%= form.text_field :line_width, id: :text_wrapper_line_width %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :text_wrapper_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/text_wrappers/edit.html.erb
<h1>Editing Text Wrapper</h1>

<%= render 'form', text_wrapper: @text_wrapper %>

<%= link_to 'Show', @text_wrapper %> |
<%= link_to 'Back', text_wrappers_path %>

app/views/text_wrappers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Texts</h1>

<table>
  <thead>
    <tr>
      <th>Line width</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  
  <tbody>
    
    <% @text_wrappers.each do |text_wrapper| %>
    <style> 
    span {
      /* add an extra line */
      display: inline-block;
      width: 100%;
    }
    p {
      /* reduce line-height to half to include spans */
      line-height: 0.6em;
      /* set a reasonnable width */
      width: <%= text_wrapper.line_width%>em;
      text-align: justify;
    }
    
    </style>
      <tr>
        <td><%= text_wrapper.line_width %></td>
        <td><%= simple_format text_wrapper.text %></div></td>
        <td><%= link_to 'Show', text_wrapper %></td>
        <td><%= link_to 'Edit', edit_text_wrapper_path(text_wrapper) %></td>
        <td><%= link_to 'Destroy', text_wrapper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text Wrapper', new_text_wrapper_path %>

app/views/text_wrappers/new.html.erb
<h1>New Text</h1>

<%= render 'form', text_wrapper: @text_wrapper %>

<%= link_to 'Back', text_wrappers_path %>

app/views/text_wrappers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line width:</strong>
  <%= @text_wrapper.line_width %>
</p>

<p>
  <strong>Text:</strong>
  <style> 
    span {
      /* add an extra line */
      display: inline-block;
      width: 100%;
    }
    p {
      /* reduce line-height to half to include spans */
      line-height: 0.6em;
      /* set a reasonnable width */
      width: <%= @text_wrapper.line_width%>em;
      text-align: justify;
    }
    </style>
  <!-- with  the line_width the developer can break the lines using the simple format within word_wrap
  to print properly in the view port
  -->
  <%= simple_format @text_wrapper.text %>
</p>

<%= link_to 'Edit', edit_text_wrapper_path(@text_wrapper) %> |
<%= link_to 'Back', text_wrappers_path %>